apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: flask-app
data:
  WORKER_HOST: "0.0.0.0"
  WORKER_PORT: "5002"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "reverse_database"
  DB_USER: "sql_user"