apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-app
type: Opaque
data:
  mysql-root-password: cm9vdF9wYXNzd29yZA==  #echo -n 'mySecurePassword' | base64
  mysql-user-password: c3FsX3Bhc3N3b3Jk