apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    storage-type: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/database-data