apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: multi-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: web-service
          image: 057724841053.dkr.ecr.us-east-1.amazonaws.com/web-service:latest
          imagePullPolicy: Always # Never - will Ensure it uses the local image and not pulling from a registry
          envFrom:
            - configMapRef:
                name: frontend-config
          ports:
            - containerPort: 5001
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
